from django.urls import path

from .views import (
    RegisterView,
    VerificationSubmitView,
    LoginView,
    MeView,
    AdminUserListView,
    AdminUserDetailView,
    AdminUserRoleView,
    AdminUserStatusView,
    AdminVerificationListView,
    AdminVerificationApproveView,
    AdminVerificationRejectView,
    StaffListView,
    PoliceOfficerListView,
    InvestigatorListView,
    ComplainantListView,
    StaffTestView,
    PoliceTestView,
    InvestigatorTestView,
    LegalTestView,
    AdminTestView,
)

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "me/",
        MeView.as_view(),
        name="me",
    ),
    path(
        "verification/",
        VerificationSubmitView.as_view(),
        name="verification-submit",
    ),

    path(
        "users/",
        AdminUserListView.as_view(),
        name="admin-user-list",
    ),
    path(
        "users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
    path(
        "users/<int:pk>/role/",
        AdminUserRoleView.as_view(),
        name="admin-user-role",
    ),
    path(
        "users/<int:pk>/status/",
        AdminUserStatusView.as_view(),
        name="admin-user-status",
    ),

    path(
        "verifications/",
        AdminVerificationListView.as_view(),
        name="admin-verification-list",
    ),
    path(
        "verifications/<int:pk>/approve/",
        AdminVerificationApproveView.as_view(),
        name="admin-verification-approve",
    ),
    path(
        "verifications/<int:pk>/reject/",
        AdminVerificationRejectView.as_view(),
        name="admin-verification-reject",
    ),

    path(
        "staff/",
        StaffListView.as_view(),
        name="staff-list",
    ),
    path(
        "police-officers/",
        PoliceOfficerListView.as_view(),
        name="police-officer-list",
    ),
    path(
        "investigators/",
        InvestigatorListView.as_view(),
        name="investigator-list",
    ),
    path(
        "complainants/",
        ComplainantListView.as_view(),
        name="complainant-list",
    ),

    path(
        "staff-test/",
        StaffTestView.as_view(),
        name="staff-test",
    ),
    path(
        "police-test/",
        PoliceTestView.as_view(),
        name="police-test",
    ),
    path(
        "investigator-test/",
        InvestigatorTestView.as_view(),
        name="investigator-test",
    ),
    path(
        "legal-test/",
        LegalTestView.as_view(),
        name="legal-test",
    ),
    path(
        "admin-test/",
        AdminTestView.as_view(),
        name="admin-test",
    ),
]