# Generated by Django 6.1 on 2026-08-30 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=255)),
                ('hearing_date', models.DateTimeField()),
                ('hearing_purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('ADJOURNED', 'Adjourned'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='court_hearings', to='cases.case')),
                ('legal_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='court_hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='LegalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('legal_opinion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_reviews', to='cases.case')),
                ('legal_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
