# Generated by Django 6.1 on 2026-08-30 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='notes',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='case',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='casehistory',
            name='action',
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fir_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CHARGESHEET_FILED', 'Chargesheet Filed'), ('COURT', 'Court'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='new_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
