# Generated by Django 6.1 on 2026-09-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_investigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_history_changes', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investigation', '-created_at'], name='inv_history_created_idx')],
            },
        ),
    ]
