# Generated by Django 6.1 on 2026-09-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('investigations', '0003_investigationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessStatementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='witness_statements/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='classification',
            field=models.CharField(choices=[('CONFIDENTIAL', 'Confidential'), ('HIGHLY_CONFIDENTIAL', 'Highly Confidential'), ('RESTRICTED', 'Restricted')], db_index=True, default='CONFIDENTIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='statement_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='witness_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='witnessstatement',
            index=models.Index(fields=['case', '-statement_date'], name='ws_case_date_idx'),
        ),
        migrations.AddIndex(
            model_name='witnessstatement',
            index=models.Index(fields=['classification', '-created_at'], name='ws_classification_created_idx'),
        ),
        migrations.AddField(
            model_name='witnessstatementmedia',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='investigations.witnessstatement'),
        ),
        migrations.AddField(
            model_name='witnessstatementmedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_witness_statement_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='witnessstatementmedia',
            index=models.Index(fields=['statement', '-created_at'], name='ws_media_statement_created_idx'),
        ),
    ]
