# Generated by Django 6.1 on 2026-09-06 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('investigations', '0004_witnessstatementmedia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='witnessstatement',
            name='ws_classification_created_idx',
        ),
        migrations.RenameIndex(
            model_name='witnessstatementmedia',
            new_name='wsm_statement_created_idx',
            old_name='ws_media_statement_created_idx',
        ),
        migrations.AlterField(
            model_name='witnessstatement',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='witnessstatement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('FINAL', 'Final'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='witnessstatementmedia',
            name='media_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='witnessstatement',
            index=models.Index(fields=['status', '-statement_date'], name='ws_status_date_idx'),
        ),
    ]
