# Generated by Django 6.1 on 2026-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NORMAL_USER', 'Normal User'), ('POLICE_OFFICER', 'Police Officer'), ('INVESTIGATOR', 'Investigator'), ('LEGAL_OFFICER', 'Legal Officer'), ('ADMIN', 'Admin')], db_index=True, default='NORMAL_USER', max_length=30),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='verification_type',
            field=models.CharField(choices=[('NORMAL_USER', 'Normal User'), ('POLICE_OFFICER', 'Police Officer'), ('INVESTIGATOR', 'Investigator'), ('LEGAL_OFFICER', 'Legal Officer')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['status', '-created_at'], name='ver_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['verification_type', 'status'], name='ver_type_status_idx'),
        ),
    ]
