# Generated by Django 6.1 on 2026-09-01 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('document_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('algorithm', models.CharField(choices=[('RSA-SHA256', 'RSA SHA-256')], default='RSA-SHA256', max_length=50)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='documents.document')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['document', '-signed_at'], name='doc_signature_created_idx'), models.Index(fields=['signed_by', '-signed_at'], name='user_signature_created_idx')],
            },
        ),
    ]
