# Generated by Django 6.1 on 2026-09-06 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('documents', '0003_documentsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentsignature',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='documentsignature',
            name='doc_signature_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentsignature',
            name='user_signature_created_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('FIR', 'FIR'), ('EVIDENCE', 'Evidence'), ('STATEMENT', 'Statement'), ('REPORT', 'Report'), ('INVESTIGATION_REPORT', 'Investigation Report'), ('COURT_ORDER', 'Court Order'), ('LEGAL_DOCUMENT', 'Legal Document'), ('CHARGE_SHEET', 'Charge Sheet'), ('MEDICAL_REPORT', 'Medical Report'), ('FORENSIC_REPORT', 'Forensic Report'), ('WITNESS_STATEMENT', 'Witness Statement'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_document_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='algorithm',
            field=models.CharField(default='RSA-SHA256', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/versions/'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
