# Generated by Django 6.1 on 2026-09-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('FIR', 'FIR'), ('POLICE_REPORT', 'Police Report'), ('INVESTIGATION_REPORT', 'Investigation Report'), ('LEGAL_DOCUMENT', 'Legal Document'), ('COURT_DOCUMENT', 'Court Document'), ('EVIDENCE', 'Evidence'), ('COMPLAINT_DOCUMENT', 'Complaint Document'), ('GENERAL', 'General'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
