# Generated by Django 6.1 on 2026-09-01 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('documents', '0002_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_a3c2bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action_766c6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_case_id_f32b2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_documen_8ae657_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ARCHIVE', 'Archive'), ('SHARE', 'Share'), ('VERIFY', 'Verify'), ('ACCESS_DENIED', 'Access Denied')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['case', '-created_at'], name='audit_case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['document', '-created_at'], name='audit_doc_created_idx'),
        ),
    ]
