# Generated by Django 6.1 on 2026-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_record_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ARCHIVE', 'Archive'), ('SHARE', 'Share'), ('VERIFY', 'Verify'), ('ACCESS_DENIED', 'Access Denied'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_STATUS_CHANGED', 'User Status Changed'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected')], db_index=True, max_length=50),
        ),
    ]
