# Generated by Django 6.1 on 2026-08-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='complaint',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED_TO_CASE', 'Converted to Case'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=30),
        ),
    ]
