# Generated by Django 6.1 on 2026-08-30 06:46

import django.core.validators
import django.db.models.deletion
import evidence.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('DIGITAL', 'Digital Evidence'), ('PHYSICAL', 'Physical Evidence'), ('DOCUMENT', 'Document'), ('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/', validators=[evidence.validators.validate_evidence_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_CUSTODY', 'In Custody'), ('UNDER_ANALYSIS', 'Under Analysis'), ('SUBMITTED', 'Submitted'), ('RELEASED', 'Released'), ('ARCHIVED', 'Archived')], default='COLLECTED', max_length=30)),
                ('collection_location', models.CharField(blank=True, max_length=500)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='cases.case')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_records', to='evidence.evidence')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
    ]
