# Generated by Django 6.1 on 2026-08-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_notes_casehistory_comment_and_more'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='collected_at',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='collection_location',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='status',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PHYSICAL', 'Physical'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='sha256_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='EvidenceCustody',
        ),
    ]
