# Generated by Django 6.1 on 2026-09-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_remove_evidence_collected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='current_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EvidenceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('TRANSFER', 'Transfer'), ('DOWNLOAD', 'Download'), ('VERIFY', 'Integrity Verification'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_activities', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='evidence.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evidence', '-created_at'], name='activity_evidence_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCustodyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INITIAL', 'Initial Custody'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], default='TRANSFER', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_transfers', to='evidence.evidence')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_custody_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_custody_to', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_evidence_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['evidence', '-transferred_at'], name='custody_evidence_date_idx'), models.Index(fields=['to_user', '-transferred_at'], name='custody_to_user_date_idx')],
            },
        ),
    ]
